site_name: SecDoc
nav:
        - Home: index.md
        - Wireless:
                - Alfa AWUS036ACH: alfa_AWUS036ACH.md
                - Crack: wireless_crack.md
        - Man in the Middle: mitm.md
        - Scan: scan.md
        
