site_name: Security Documentation
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: 'dracula' 
  highlightjs: true
  hljs_languages:
      - bash
      - python 
markdown_extensions:
  - admonition
nav:
        - Home: index.md
        - Wireless:
                - Alfa AWUS036ACH: alfa_AWUS036ACH.md
                - Crack: wireless_crack.md
        - Man in the Middle: mitm.md
        - Scan: scan.md
